name: MacOS build

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Build MacOS electrum
        run: ./contrib/osx/make_osx

      - name: Set version env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

      - uses: Shopify/upload-to-release@master
        with:
          name: electrum-${{ env.RELEASE_VERSION }}.dmg
          path: ./dist/electrum-${{ env.RELEASE_VERSION }}.dmg
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          content-type: application/x-apple-diskimage
