name: MacOS build

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Build MacOS electrum
        run: ./contrib/osx/make_osx

      - name: Set version env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
        
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/electrum-${{ env.RELEASE_VERSION }}.dmg
          asset_name: electrum-${{ env.RELEASE_VERSION }}.dmg
          tag: ${{ github.ref }}
          overwrite: true
