name: Windows Electrum

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install apt dependencies
        run: sudo apt-get install -y libsecp256k1-0
      - name: Install deps
        run: pip install requests
      - name: Locale updates
        run: ./contrib/pull_locale
      - name: Build via docker
        run: sudo docker build --no-cache -t electrum-wine-builder-img ./contrib/build-wine/
      - name: Run docker build
        run: sudo docker run --name electrum-wine-builder-cont -v $PWD:/opt/wine64/drive_c/electrum --rm --workdir /opt/wine64/drive_c/electrum/contrib/build-wine electrum-wine-builder-img ./build.sh

      - name: Set version env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

      - uses: Shopify/upload-to-release@1.0.0
        with:
          name: electrum-${{ env.RELEASE_VERSION }}-portable.exe
          path: ./contrib/build-wine/dist/electrum-${{ env.RELEASE_VERSION }}-portable.exe
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          content-type: application/vnd.microsoft.portable-executable

      - uses: Shopify/upload-to-release@1.0.0
        with:
          name: electrum-${{ env.RELEASE_VERSION }}.exe
          path: ./contrib/build-wine/dist/electrum-${{ env.RELEASE_VERSION }}.exe
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          content-type: application/vnd.microsoft.portable-executable

      - uses: Shopify/upload-to-release@1.0.0
        with:
          name: electrum-${{ env.RELEASE_VERSION }}-setup.exe
          path: ./contrib/build-wine/dist/electrum-${{ env.RELEASE_VERSION }}-setup.exe
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          content-type: application/vnd.microsoft.portable-executable
