name: Windows Electrum

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install apt dependencies 
      run: sudo apt-get install -y libsecp256k1-0
    - name: Install deps
      run: pip install requests
    - name: Locale updates 
      run: ./contrib/pull_locale
    - name: Build via docker
      run: ./contrib/make_packages && sudo docker build --no-cache -t electrum-android-builder-img electrum/gui/kivy/tools
    - name: Change ownership
      run: sudo chown -R 1000:1000 .
    - name: Run docker build
      run: sudo docker run -it -u 1000:1000 --rm --name electrum-android-builder-cont --env CI=true -v $PWD:/home/user/wspace/electrum --workdir /home/user/wspace/electrum electrum-android-builder-img ./contrib/make_apk
    - name: Clean up
      run: kill %1 && ls -la bin && if [ $(ls bin | grep -c Electrum-*) -eq 0 ]; then exit 1; fi
