name: Windows Electrum

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install apt dependencies 
      run: sudo apt-get install -y libsecp256k1-0
    - name: Install deps
      run: pip install requests
    - name: Locale updates 
      run: ./contrib/pull_locale
    - name: Build via docker
      run: sudo docker build --no-cache -t electrum-wine-builder-img ./contrib/build-wine/
    - name: Run docker build
      run: sudo docker run --name electrum-wine-builder-cont -v $PWD:/opt/wine64/drive_c/electrum --rm --workdir /opt/wine64/drive_c/electrum/contrib/build-wine electrum-wine-builder-img ./build.sh
    - name: Clean up
      run: kill %1 && ls -la bin && if [ $(ls bin | grep -c Electrum-*) -eq 0 ]; then exit 1; fi
